# Generated by Django 3.2.25 on 2025-05-02 06:07

import commonsServer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snapshotServer', '0027_testcaseinsession_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', commonsServer.models.TruncatingCharField(default='', max_length=250, null=True)),
                ('exception', models.CharField(default='', max_length=100, null=True)),
                ('errorMessage', models.CharField(default='', max_length=1000, null=True)),
                ('cause', models.CharField(max_length=100, null=True)),
                ('relatedErrors', models.ManyToManyField(related_name='_snapshotServer_error_relatedErrors_+', to='snapshotServer.Error')),
                ('stepResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='snapshotServer.stepresult')),
            ],
        ),
        migrations.AlterField(
            model_name='testcaseinsession',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ErrorCauseDetected',
        ),
    ]
